---
# Default HAOS VM configuration variables

# Unique VM identifier for HAOS.
vmid: "{{ lookup('pipe','pvesh get /cluster/nextid') | trim }}"

# Hostname for the HAOS VM.
hostname: "Home Assistant OS"

# Number of CPU cores assigned.
cores: 2

# Amount of RAM allocated in MiB.
ram: 4096          # in MiB

# Disk size for the HAOS VM.
disk_size: "32G"

# Network bridge used by the HAOS VM.
bridge: "vmbr0"

# CPU type configuration.
cpu_type: "-cpu host"

# Disk cache settings.
disk_cache: "cache=writethrough,"

# HAOS version identifier.
haos_version: "stable"

# URL to download the HAOS VM image.
haos_url: "https://github.com/home-assistant/operating-system/releases/download/{{ haos_version }}/haos_ova-{{ haos_version }}.qcow2.xz"

# Whether to start the VM after creation.
start_vm: true

# Destination filename for the HAOS image.
dest_image: "haos_ova-{{ haos_version }}.qcow2"

# Filename for the extracted HAOS image.
extracted_image: "haos_ova-{{ haos_version }}.qcow2"
