---
galaxy_info:
  role_name: install_caddy
  author: your name
  description: "Installs and configures Caddy for reverse proxying LXC containers."
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
dependencies: []
