---
opnsense_vm_id: "{{ lookup('pipe', 'pvesh get /cluster/nextid') | trim }}"
opnsense_hostname: "OpnSense"
opnsense_disk_size: "8G"
opnsense_cpu_cores: 4
opnsense_ram: 8192
opnsense_storage: "local-lvm"
opnsense_bridge: "vmbr0"
opnsense_network: ""
opnsense_mac: "02:{{ 99999 | random(seed=inventory_hostname) | string | regex_replace('(..)', '\\1:') | regex_replace(':$', '') }}"
opnsense_method: "default"
# ...existing defaults...
