---
# Extend proxmox_vm_defaults with OPNsense specific settings
opnsense_vm_id: ""
opnsense_vm_name: "opnsense"
opnsense_vm_template: "local:iso/opnsense.iso"

# Override proxmox_vm_defaults for OPNsense requirements
opnsense_vm_memory: 2048
opnsense_vm_cores: 2
opnsense_vm_disk_size: "16G"

# Network interfaces (uses proxmox_vm_defaults network settings as base)
opnsense_wan_network:
  bridge: "vmbr0"
  model: "{{ proxmox_vm_defaults.network_model }}"
  tag: ""  # VLAN tag if needed
  firewall: true

opnsense_lan_network:
  bridge: "vmbr1"
  model: "{{ proxmox_vm_defaults.network_model }}"
  tag: ""  # VLAN tag if needed
  firewall: true

# OPNsense specific settings
opnsense_version: "latest"
opnsense_root_password: ""  # Must be set in vault
opnsense_admin_password: ""  # Must be set in vault

# Initial configuration
opnsense_hostname: "opnsense"
opnsense_domain: "local"
opnsense_timezone: "UTC"
opnsense_ntp_servers: ["0.pool.ntp.org", "1.pool.ntp.org"]

# WAN configuration
opnsense_wan_dhcp: true
opnsense_wan_ip: ""  # Used if DHCP is false
opnsense_wan_gateway: ""  # Used if DHCP is false
opnsense_wan_dns: ["1.1.1.1", "8.8.8.8"]

# LAN configuration
opnsense_lan_ip: "192.168.1.1"
opnsense_lan_netmask: "24"
opnsense_lan_dhcp_enabled: true
opnsense_lan_dhcp_range_start: "192.168.1.100"
opnsense_lan_dhcp_range_end: "192.168.1.200"
