---
galaxy_info:
  role_name: create_lxc_container
  author: Your Name  # Replace with the actual author
  description: >
An Ansible role to create and update LXC containers on Proxmox VE,
optimized for hosting Docker and other containerized applications.
  license: MIT
  min_ansible_version: 2.9 # community.general.proxmox_lxc needs >= 2.9
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - proxmox
    - lxc
    - container
    - docker

collections:
  - community.general # Required for proxmox_lxc module
