---
- name: Configure monitoring network
  community.docker.docker_network:
    name: monitoring
    driver: bridge
    ipam_config:
      - subnet: "{{ network.vlans.mgmt.subnet }}"

- name: Deploy Prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
    mode: "0644"
  notify: restart prometheus
