---
# =============================================================================
# SSH Security Configuration Tasks
# =============================================================================

- name: Configure SSH daemon
  ansible.builtin.template:
    src: security/sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when: security_config.ssh is defined
  tags: ["security", "ssh"]

- name: Configure SSH authorized keys
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.key }}"
  loop: "{{ security_config.ssh_keys | default([]) }}"
  when: security_config.ssh_keys is defined
  tags: ["security", "ssh"]

- name: Ensure SSH directory permissions
  ansible.builtin.file:
    path: "/etc/ssh"
    state: directory
    mode: "0755"
    owner: root
    group: root
  tags: ["security", "ssh"]

- name: Ensure SSH host keys have secure permissions
  ansible.builtin.file:
    path: "/etc/ssh/{{ item }}"
    mode: "0600"
    owner: root
    group: root
  with_fileglob:
    - "/etc/ssh/ssh_host_*_key"
  tags: ["security", "ssh"]
