---
# =============================================================================
# System Security Tasks
# =============================================================================
# This file manages system-level security configuration for Proxmox VE

- name: Configure system security
  block:
    - name: Configure SSH settings
      ansible.builtin.template:
        src: sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: "0600"
        validate: /usr/sbin/sshd -t -f %s
      notify: restart ssh

    - name: Configure PAM limits
      ansible.builtin.template:
        src: pam_limits.conf.j2
        dest: /etc/security/limits.d/99-proxmox.conf
        mode: "0644"

  tags: ["security", "system"]
