- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - git
      - build-essential
      - pkgconf
      - libssl-dev
      - libmariadb-dev-compat
      - libpq-dev
      - argon2
      - curl
    state: present

- name: Get latest Vaultwarden release tag
  shell: >
    curl -fsSL https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest |
    grep '"tag_name":' | cut -d '"' -f4
  register: vaultwarden_release
  changed_when: false

- name: Clone Vaultwarden repository
  git:
    repo: 'https://github.com/dani-garcia/vaultwarden.git'
    dest: /tmp/vaultwarden
    version: "{{ vaultwarden_release.stdout }}"
    force: yes

- name: Build Vaultwarden using cargo
  shell: |
    cd /tmp/vaultwarden && cargo build --release
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Create vaultwarden directories
  file:
    path: "{{ item }}"
    state: directory
    owner: vaultwarden
    group: vaultwarden
    mode: '0755'
  loop:
    - /opt/vaultwarden/bin
    - /opt/vaultwarden/data
    - /opt/vaultwarden/web-vault

- name: Copy Vaultwarden binary
  copy:
    src: /tmp/vaultwarden/target/release/vaultwarden
    dest: /opt/vaultwarden/bin/vaultwarden
    mode: '0755'

- name: Get latest Web-Vault release tag
  shell: >
    curl -fsSL https://api.github.com/repos/dani-garcia/bw_web_builds/releases/latest |
    grep '"tag_name":' | cut -d '"' -f4
  register: webvault_release
  changed_when: false

- name: Download Web-Vault archive
  shell: |
    curl -fsSL -o /tmp/bw_web.tar.gz https://github.com/dani-garcia/bw_web_builds/releases/download/{{ webvault_release.stdout }}/bw_web_{{ webvault_release.stdout }}.tar.gz
  args:
    creates: /tmp/bw_web.tar.gz

- name: Extract Web-Vault assets
  unarchive:
    src: /tmp/bw_web.tar.gz
    dest: /opt/vaultwarden/
    remote_src: yes

- name: Create Vaultwarden .env file
  copy:
    dest: /opt/vaultwarden/.env
    content: |
      ADMIN_TOKEN='{{ admin_token }}'
      ROCKET_ADDRESS=0.0.0.0
      DATA_FOLDER=/opt/vaultwarden/data
      DATABASE_URL={{ database_url }}
      WEB_VAULT_ENABLED=true
    owner: vaultwarden
    group: vaultwarden
    mode: '0644'

- name: Create systemd service for Vaultwarden
  copy:
    dest: /etc/systemd/system/vaultwarden.service
    content: |
      [Unit]
      Description=Vaultwarden Server
      After=network.target

      [Service]
      User=vaultwarden
      Group=vaultwarden
      EnvironmentFile=-/opt/vaultwarden/.env
      ExecStart=/opt/vaultwarden/bin/vaultwarden
      Restart=always
      LimitNOFILE=65535

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd configuration
  systemd:
    daemon_reload: yes

- name: Enable and restart Vaultwarden service
  systemd:
    name: vaultwarden
    enabled: yes
    state: restarted
