---
# =============================================================================
# Local Storage Configuration Tasks
# =============================================================================

- name: Configure local storage
  ansible.builtin.command:
    cmd: >-
      pvesm set local
      --enable {{ item.enabled | default(1) }}
      --content {{ item.content | join(',') }}
      {% if item.path is defined %}--path {{ item.path }}{% endif %}
      {% if item.maxfiles is defined %}--maxfiles {{ item.maxfiles }}{% endif %}
  loop: "{{ storage_config.local | default([]) }}"
  when: storage_config.local is defined
  notify: reload storage
  tags: ["storage", "local"]

- name: Configure local-lvm storage
  ansible.builtin.command:
    cmd: >-
      pvesm set local-lvm
      --enable {{ item.enabled | default(1) }}
      --content {{ item.content | join(',') }}
      {% if item.vgname is defined %}--vgname {{ item.vgname }}{% endif %}
      {% if item.thin is defined %}--thin {{ item.thin | int }}{% endif %}
  loop: "{{ storage_config.local_lvm | default([]) }}"
  when: storage_config.local_lvm is defined
  notify: reload storage
  tags: ["storage", "local", "lvm"]

- name: Configure directory permissions
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  loop: "{{ storage_config.local | default([]) }}"
  when:
    - storage_config.local is defined
    - item.path is defined
  tags: ["storage", "local"]
