---
# handlers file for create_lxc_container

- name: Wait for container readiness
  ansible.builtin.wait_for:
    host: "{{ hostvars[inventory_hostname][lxc_ip_fact_name] | default(lxc_network_config.net0.ip.split('/')[0] | default('')) }}" # Use fetched IP or fallback to static IP
    port: 22 # Default SSH port
    delay: 10 # Initial delay before first check
    timeout: "{{ lxc_wait_timeout }}"
    state: started
    msg: "Timeout waiting for SSH on container {{ lxc_id }} at {{ hostvars[inventory_hostname][lxc_ip_fact_name] | default('unknown IP') }}"
  delegate_to: localhost
  when:
    - hostvars[inventory_hostname][lxc_ip_fact_name] is defined or
      (lxc_network_config.net0 is defined and lxc_network_config.net0.ip is defined and lxc_network_config.net0.ip != 'dhcp')
  # become: false # Handler runs on controller
  # Ignore errors if SSH isn't expected (e.g., minimal image without SSH)
  # ignore_errors: true
