---
- name: Enable/Disable HA Services
  ansible.builtin.systemd:
    name: "{{ item.name }}"
    enabled: "{{ enable_ha }}"
    state: "{{ 'started' if enable_ha else 'stopped' }}"
  loop:
    - { name: "pve-ha-lrm", comment: "HA Local Resource Manager" }
    - { name: "pve-ha-crm", comment: "HA Cluster Resource Manager" }
    - { name: "corosync", comment: "Cluster messaging system" }
  loop_control:
    label: "{{ item.name }} - {{ item.comment }}"
