---
- name: Update package cache and perform distribution upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes # Equivalent to apt-get autoremove after upgrade
  register: apt_dist_upgrade
  until: apt_dist_upgrade is succeeded # Retry apt tasks if they fail temporarily
  retries: 3
  delay: 5
  # Retry up to 3 times with a 5-second delay between attempts to handle temporary network or repository issues.
  notify: Restart pveproxy # Notify handler after update
