---
# =============================================================================
# Proxmox VE Role Tasks
# =============================================================================

# Pre-Installation
# -----------------------------------------------------------------------------
- name: Validate configuration
  ansible.builtin.import_tasks: validate.yml
  tags: ["validate", "pre-install"]

- name: Configure package repositories
  ansible.builtin.import_tasks: repository.yml
  tags: ["repository", "pre-install"]

# System Configuration
# -----------------------------------------------------------------------------
- name: Configure base system
  ansible.builtin.import_tasks: system.yml
  tags: ["system"]

- name: Configure firmware
  ansible.builtin.import_tasks: firmware.yml
  tags: ["firmware", "system"]

- name: Configure power management
  ansible.builtin.import_tasks: power.yml
  tags: ["power", "system"]

- name: Configure security settings
  ansible.builtin.import_tasks: security.yml
  tags: ["security", "system"]

# Network & Storage
# -----------------------------------------------------------------------------
- name: Configure network
  ansible.builtin.import_tasks: network.yml
  tags: ["network"]
  when: network_config is defined

- name: Configure storage
  ansible.builtin.import_tasks: storage.yml
  tags: ["storage"]
  when: storage_config is defined

# Virtualization
# -----------------------------------------------------------------------------
- name: Configure virtual machines
  ansible.builtin.import_tasks: vm.yml
  tags: ["vm", "virtualization"]
  when: proxmox_vm is defined

- name: Configure LXC containers
  ansible.builtin.import_tasks: lxc.yml
  tags: ["lxc", "virtualization"]
  when: proxmox_lxc is defined

- name: Configure VM resources
  ansible.builtin.import_tasks: resources.yml
  tags: ["resources", "virtualization"]
  when: proxmox_vm is defined

# High Availability
# -----------------------------------------------------------------------------
- name: Configure cluster
  ansible.builtin.import_tasks: cluster.yml
  tags: ["cluster", "ha"]
  when: proxmox_cluster.enabled | bool

- name: Configure high availability
  ansible.builtin.import_tasks: ha.yml
  tags: ["ha"]
  when: proxmox_ha.enabled | bool

# Operations
# -----------------------------------------------------------------------------
- name: Configure backup
  ansible.builtin.import_tasks: backup.yml
  tags: ["backup", "operations"]
  when: proxmox_backup.enabled | bool

- name: Configure monitoring
  ansible.builtin.import_tasks: monitoring.yml
  tags: ["monitoring", "operations"]
  when: proxmox_monitoring is defined

- name: Configure email notifications
  ansible.builtin.import_tasks: email.yml
  tags: ["email", "operations"]
  when: proxmox_email.enabled | bool

# Post-configuration Tasks
# -----------------------------------------------------------------------------
- name: Include post-configuration tasks
  ansible.builtin.import_tasks: post/main.yml
  tags: ["post-config"]

# Configure VM resources
- name: Configure VM resources
  ansible.builtin.import_tasks: vm_resources.yml
  when: proxmox_vm is defined
  tags:
    - proxmox
    - vm
    - resources 
