---
- name: Restart pveproxy
  ansible.builtin.service: # Use FQCN
    name: pveproxy
    state: restarted

- name: Reinstall proxmox-widget-toolkit # Name matches notify
  ansible.builtin.apt:
    name: proxmox-widget-toolkit
    state: present
    reinstall: yes
