---
# defaults file for setup_jellyfin_lxc

jellyfin_apt_key_url: https://repo.jellyfin.org/jellyfin_team.gpg.key
jellyfin_apt_repo_url: https://repo.jellyfin.org/{{ ansible_distribution | lower }}
jellyfin_apt_repo_suite: "{{ ansible_distribution_release | lower }}"
jellyfin_apt_repo_component: main
jellyfin_package_version: latest # Pin to a specific version if needed, e.g., "10.8.10"

# User and group under which Jellyfin runs (managed by the package)
jellyfin_user: jellyfin
jellyfin_group: jellyfin

# --- Feature Flags ---

# Install ffmpeg package (highly recommended)
jellyfin_install_ffmpeg: true

# Install mc (Midnight Commander file manager - convenience)
jellyfin_install_mc: false

# Attempt to set up Intel Quick Sync Video (QSV) hardware acceleration
# Requires host device passthrough (/dev/dri) configured in LXC settings (e.g., via create_lxc_container role)
jellyfin_setup_intel_qsv: true

# APT component needed for non-free Intel drivers on Debian
# Debian < 12 typically uses 'non-free'. Debian >= 12 uses 'non-free-firmware'
debian_non_free_component: "{{ 'non-free-firmware' if (ansible_distribution == 'Debian' and ansible_distribution_major_version | int >= 12) else 'non-free' }}"

# --- Additional Options ---

# Timezone synchronization
jellyfin_synchronize_timezone: true
