---
# tasks file for setup_docker_lxc

# Set LXC container parameters
- name: Set LXC container parameters
  ansible.builtin.set_fact:
    lxc_params:
      name: "{{ docker_lxc_name }}"
      id: "{{ docker_lxc_id | default(lookup('pipe','pvesh get /cluster/nextid') | trim) }}"
      template: "{{ docker_lxc_template }}"
      memory: "{{ docker_lxc_memory }}"
      swap: "{{ docker_lxc_swap }}"
      cores: "{{ docker_lxc_cores }}"
      disk_size: "{{ docker_lxc_disk_size }}"
      features: "{{ docker_lxc_features }}"
      description: |
        Docker LXC Container
        Created: {{ ansible_date_time.iso8601 }}

# Docker Installation and Configuration
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - curl
      - gpg
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: true

- name: Check if Docker is already installed
  ansible.builtin.command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false
  check_mode: false

- name: Install Docker Engine
  block:
    - name: Download Docker installation script
      ansible.builtin.get_url:
        url: "{{ docker_get_script_url }}"
        dest: "/tmp/get-docker.sh"
        mode: "0755"
      when: docker_check.rc != 0

    - name: Execute Docker installation script
      ansible.builtin.command:
        cmd: "sh /tmp/get-docker.sh"
      register: docker_install
      changed_when: docker_install.rc == 0
      when: docker_check.rc != 0
      notify: restart docker

    - name: Create Docker configuration directory
      ansible.builtin.file:
        path: "/etc/docker"
        state: directory
        mode: "0755"

    - name: Configure Docker daemon
      ansible.builtin.copy:
        content: "{{ docker_daemon_config }}"
        dest: "/etc/docker/daemon.json"
        mode: "0644"
      notify: restart docker

# Docker Compose Installation
- name: Install Docker Compose
  block:
    - name: Download Docker Compose
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: "0755"
      when: install_docker_compose | bool

    - name: Create Docker Compose directory
      ansible.builtin.file:
        path: "{{ docker_compose_directory }}"
        state: directory
        mode: "0755"
      when: install_docker_compose | bool

# User Management
- name: Configure Docker users
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
  notify: restart docker

# Optional Portainer Installation
- name: Install Portainer
  community.docker.docker_container:
    name: portainer
    image: "{{ portainer_image }}"
    state: started
    restart_policy: always
    published_ports: "{{ portainer_ports }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  when: install_portainer | bool

# Cleanup
- name: Clean up installation files
  ansible.builtin.file:
    path: "/tmp/get-docker.sh"
    state: absent

handlers:
  - name: restart docker
    ansible.builtin.systemd:
      name: docker
      state: restarted
      enabled: true
