---
- name: Gather monitoring services status
  community.docker.docker_container_info:
    name: "{{ item }}"
  register: container_info
  loop:
    - prometheus
    - alertmanager
    - grafana
    - node_exporter

- name: Report services status
  debug:
    msg: >
      Service {{ item.container.Name }} is {{ item.container.State.Status }}
      (uptime: {{ item.container.State.StartedAt | to_datetime | elapsed }})
  loop: "{{ container_info.results }}"
  when: item.container is defined
