---
# Service tasks for qBittorrent

- name: Create qBittorrent service
  ansible.builtin.template:
    src: qbittorrent-nox.service.j2
    dest: /etc/systemd/system/qbittorrent-nox.service
    mode: "0644"
  notify: reload systemd

- name: Ensure qBittorrent service is in desired state
  ansible.builtin.systemd:
    name: qbittorrent-nox
    state: "{{ qbittorrent.service.state }}"
    enabled: "{{ qbittorrent.service.enabled }}"
    daemon_reload: true
