---
- name: Configure media applications network
  community.docker.docker_network:
    name: media
    driver: bridge
    ipam_config:
      - subnet: "{{ network.vlans.media.subnet }}"

- name: Wait for applications to be ready
  uri:
    url: "http://{{ item }}:{{ media_stack.arr_apps[item].port }}/api/v1/system/status"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  loop:
    - prowlarr
    - sonarr
    - radarr
  when: media_stack.arr_apps[item].enabled
