---
# *Arr apps role defaults

# User configuration
arr_user: "arruser"
arr_uid: 2002
arr_group: "mediagroup"
arr_gid: 2000

# Container configuration
arr_container:
  memory: 4096
  cores: 2
  disk: "20G"
  features:
    nesting: true
    mount: "nfs,cifs"

# Application paths
arr_config_base: "/config"
arr_media_paths:
  downloads:
    incomplete: "/media/downloads/incomplete"
    complete: "/media/downloads/complete"
    categories:
      movies: "/media/downloads/complete/movies"
      tv: "/media/downloads/complete/tv"
      music: "/media/downloads/complete/music"
      books: "/media/downloads/complete/books"
  library:
    movies: "/media/media/Movies"
    tv: "/media/media/TV"
    music: "/media/media/Music"
    books:
      root: "/media/media/Books"
      ebooks: "/media/media/Books/eBooks"
      audiobooks: "/media/media/Books/Audiobooks"

# Default permissions
arr_directory_mode: "0755"

# Remote storage configuration
arr_remote_storage:
  enabled: false
  type: "nfs"
  server: ""
  share_path: ""
  mount_point: "/media"
  mount_opts: "defaults"
  nfs_opts: "rw,sync,hard,intr"
  cifs_username: ""
  cifs_password: ""
  cifs_domain: ""

# Application Configuration
arr_apps:
  radarr:
    container_name: "radarr"
    image: "linuxserver/radarr:latest"
    port: 7878
    config_path: "/config/radarr"
    media_paths:
      downloads: "{{ arr_media_paths.downloads }}"
      movies: "{{ arr_media_paths.library.movies }}"
  
  sonarr:
    container_name: "sonarr"
    image: "linuxserver/sonarr:latest"
    port: 8989
    config_path: "/config/sonarr"
    media_paths:
      downloads: "{{ arr_media_paths.downloads }}"
      tv: "{{ arr_media_paths.library.tv }}"
  
  lidarr:
    container_name: "lidarr"
    image: "linuxserver/lidarr:latest"
    port: 8686
    config_path: "/config/lidarr"
    media_paths:
      downloads: "{{ arr_media_paths.downloads }}"
      music: "{{ arr_media_paths.library.music }}"
  
  readarr:
    container_name: "readarr"
    image: "linuxserver/readarr:latest"
    port: 8787
    config_path: "/config/readarr"
    media_paths:
      downloads: "{{ arr_media_paths.downloads }}"
      books: "{{ arr_media_paths.library.books }}"

# Download client configuration
arr_download_client:
  enabled: true
  type: "qbittorrent"
  host: "qbittorrent"
  port: 8080
  username: "admin"
  password: "adminadmin"
  ssl: false
  category: "arr"

