---
# This playbook configures settings for the deployed media apps.
- name: Configure Prowlarr settings
  ansible.builtin.debug:
    msg: "Configuring Prowlarr settings..."

- name: "Configure Sonarr"
  template:
    src: "templates/sonarr_config.j2"
    dest: "/etc/sonarr/config.conf"
  when: sonarr_enabled | default(false)

- name: "Configure Radarr"
  template:
    src: "templates/radarr_config.j2"
    dest: "/etc/radarr/config.conf"
  when: radarr_enabled | default(false)

- name: "Configure Lidarr"
  template:
    src: "templates/lidarr_config.j2"
    dest: "/etc/lidarr/config.conf"
  when: lidarr_enabled | default(false)

- name: "Configure Bazarr"
  template:
    src: "templates/bazarr_config.j2"
    dest: "/etc/bazarr/config.conf"
  when: bazarr_enabled | default(false)

- name: "Configure Readarr"
  template:
    src: "templates/readarr_config.j2"
    dest: "/etc/readarr/config.conf"
  when: readarr_enabled | default(false)

- name: "Configure Recyclarr"
  template:
    src: "templates/recyclarr_config.j2"
    dest: "/etc/recyclarr/config.conf"
  when: recyclarr_enabled | default(false)
