---
# Deploy Lidarr container
- name: Deploy Lidarr container
  community.docker.docker_container:
    name: "{{ arr_apps.lidarr.container_name }}"
    image: "{{ arr_apps.lidarr.image }}"
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ arr_apps.lidarr.puid | default('1000') }}"
      PGID: "{{ arr_apps.lidarr.pgid | default('1000') }}"
      TZ: "{{ arr_timezone }}"
    volumes:
      - "{{ arr_config_base }}/lidarr:/config"
      - "{{ arr_downloads_path }}:/downloads"
      - "{{ arr_music_path }}:/music"
    ports:
      - "{{ arr_apps.lidarr.port }}:8686"
    networks:
      - name: "{{ arr_docker_network_name }}"
    labels:
      com.github.containers.toolbox: false
    memory: "{{ arr_apps.lidarr.memory | default('1g') }}"
    memory_swap: "{{ arr_apps.lidarr.memory_swap | default('-1') }}"
    cpu_shares: "{{ arr_apps.lidarr.cpu_shares | default(1024) }}"
