---
# Deploy Radarr container
- name: Deploy Radarr container
  community.docker.docker_container:
    name: "{{ arr_apps.radarr.container_name }}"
    image: "{{ arr_apps.radarr.image }}"
    state: started
    restart_policy: unless-stopped
    env:
      PUID: "{{ arr_apps.radarr.puid | default('1000') }}"
      PGID: "{{ arr_apps.radarr.pgid | default('1000') }}"
      TZ: "{{ arr_timezone }}"
    volumes:
      - "{{ arr_config_base }}/radarr:/config"
      - "{{ arr_downloads_path }}:/downloads"
      - "{{ arr_movies_path }}:/movies"
    ports:
      - "{{ arr_apps.radarr.port }}:7878"
    networks:
      - name: "{{ arr_docker_network_name }}"
    labels:
      com.github.containers.toolbox: false
    memory: "{{ arr_apps.radarr.memory | default('1g') }}"
    memory_swap: "{{ arr_apps.radarr.memory_swap | default('-1') }}"
    cpu_shares: "{{ arr_apps.radarr.cpu_shares | default(1024) }}"
