---
# =============================================================================
# Backup Configuration Default Variables
# =============================================================================

# Basic Backup Configuration
# -----------------------------------------------------------------------------
proxmox_backup:
  enabled: false
  storage: "local"
  backup_dir: "/var/lib/vz/dump"
  restore_dir: "/var/lib/vz/restore"
  mode: "snapshot" # snapshot, suspend, or stop
  compress: "zstd" # Compression algorithm

  # Backup Schedule
  schedule:
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "*"

  # Retention Settings
  retention:
    keep_last: 7 # Number of backups to keep
    keep_hourly: 24 # Hourly backups to keep
    keep_daily: 7 # Daily backups to keep
    keep_weekly: 4 # Weekly backups to keep
    keep_monthly: 2 # Monthly backups to keep

  # Restore Configuration
  restore:
    enabled: true
    verify: true # Verify backup before restore
    bandwidth_limit: 0 # 0 means unlimited

  # Email Notifications
  notifications:
    enabled: false
    on_success: false
    on_failure: true
    mailto: ""

  # Performance Settings
  performance:
    bandwidth_limit: 0 # 0 means unlimited
    ionice: 5 # IO priority (0-7)
    max_workers: 1 # Maximum parallel backup jobs

  # PBS Configuration
  pbs:
    enabled: false
    remove_subscription_nag: true
    motd_enabled: true
    web_interface_port: 8007

    # PBS Storage Configuration
    storage:
      path: "/var/lib/proxmox-backup"
      gc_schedule: "daily"
      prune_schedule: "daily"

    # PBS Authentication
    authentication:
      realm: "pbs"
      token_lifetime: 28800

    # PBS Network Settings
    network:
      bind_address: "0.0.0.0"
      port: 8007

    # Dependencies
    dependencies:
      - gpg
      - proxmox-backup-server

    # Monitoring
    monitoring:
      enabled: true
      interval: 300
      metrics:
        - backup_status
        - storage_usage
        - task_status
