---
# System Configuration
# -----------------------------------------------------------------------------
proxmox_hostname: ""
proxmox_timezone: "UTC"
proxmox_locale: "en_US.UTF-8"
proxmox_keyboard_layout: "us"

# System Performance Configuration
proxmox_sysctl:
  # VM/CT Memory Management
  vm_swappiness: 10
  vm_overcommit_memory: 1
  vm_min_free_kbytes: 262144
  vm_dirty_ratio: 20
  vm_dirty_background_ratio: 10

  # Network Performance
  net_core_somaxconn: 1024
  net_core_netdev_max_backlog: 5000
  net_ipv4_tcp_max_syn_backlog: 4096
  net_ipv4_tcp_fastopen: 3
  net_ipv4_tcp_tw_reuse: 1

  # File System & I/O
  fs_file_max: 1048576
  fs_inotify_max_user_watches: 524288
  fs_aio_max_nr: 1048576

# CPU Configuration
proxmox_cpu:
  governor: "schedutil"
  mitigations: false
  intel_pstate: "performance"
  amd_pstate: "performance"

# Storage Performance
proxmox_storage_optimizations:
  zfs_arc_max: "{{ (ansible_memtotal_mb * 0.5) | int }}M"
  zfs_options:
    compression: "lz4"
    atime: "off"
    xattr: "sa"
  ext4_options: "noatime,nodiratime,discard"
