---
# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Allow long code blocks
  code_blocks: false
  # Allow long tables
  tables: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  # Only check sibling headings
  siblings_only: true

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML tags
  allowed_elements:
    - br
    - details
    - summary

# MD041/first-line-heading/first-line-h1 - First line in file should be a top level heading
MD041: true

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: "fenced"
