---
# =============================================================================
# Proxmox Service Manager Role Handlers
# =============================================================================

- name: restart service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: restarted
  when: service_name is defined

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: reloaded
  when: service_name is defined 
