---
# =============================================================================
# Cluster Network Configuration Tasks
# =============================================================================

- name: Configure corosync network
  ansible.builtin.template:
    src: cluster/corosync.conf.j2
    dest: /etc/corosync/corosync.conf
    mode: "0644"
  when:
    - cluster_config.enabled | default(false)
    - cluster_config.network is defined
  notify: reload corosync
  tags: ["cluster", "network"]

- name: Configure cluster network interfaces
  ansible.builtin.template:
    src: cluster/interfaces.j2
    dest: /etc/network/interfaces.d/cluster
    mode: "0644"
  when:
    - cluster_config.enabled | default(false)
    - cluster_config.network.interfaces is defined
  notify: restart networking
  tags: ["cluster", "network"]

- name: Configure cluster firewall
  ansible.builtin.template:
    src: cluster/cluster.fw.j2
    dest: /etc/pve/firewall/cluster.fw
    mode: "0644"
  when:
    - cluster_config.enabled | default(false)
    - cluster_config.network.firewall is defined
  notify: reload firewall
  tags: ["cluster", "network"]

- name: Configure cluster DNS
  ansible.builtin.template:
    src: cluster/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"
  when:
    - cluster_config.enabled | default(false)
    - cluster_config.network.dns is defined
  tags: ["cluster", "network"]

- name: Configure cluster hosts
  ansible.builtin.template:
    src: cluster/hosts.j2
    dest: /etc/hosts
    mode: "0644"
  when:
    - cluster_config.enabled | default(false)
    - cluster_config.network.hosts is defined
  tags: ["cluster", "network"]
